services:
  postgres:
    image: postgres:17
    container_name: "postgres"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend

  book-service:
    build:
      context: ./book-service
      args:
        APP_PORT: 
    container_name: "book-service"
    ports:
      - "8082:8082"
    volumes:
      - ./books_files:/app/books_files
      - ./covers_files:/app/covers_files
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_HOST: "book-service"
      APP_PORT: 8082
      DB_URL: ${BOOK_SERVICE_DB_URL}
      DB_USER: ${BOOK_SERVICE_DB_USERNAME}
      DB_PASSWORD: ${BOOK_SERVICE_DB_PASSWORD}
      DB_NAME: ${BOOK_SERVICE_DB_NAME}
      DB_HOST: ${BOOK_SERVICE_DB_HOST}
    networks:
      - backend

networks:
  backend:
    driver: bridge