services:
  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend

  postgres:
    image: postgres:17
    container_name: "postgres"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend

  gateway:
    build:
      context: ./api-gateway
      args:
        APP_PORT: 
    container_name: "gateway"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      APP_HOST: "gateway"
      APP_PORT: 8080
      REDIS_HOST: ${GATEWAY_REDIS_HOST}
      REDIS_PORT: ${GATEWAY_REDIS_PORT}
    networks:
      - backend

  book-service:
    build:
      context: ./book-service
      args:
        APP_PORT: 
    container_name: "book-service"
    ports:
      - "8082:8082"
    volumes:
      - ./books_files:/app/books_files
      - ./covers_files:/app/covers_files
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      APP_HOST: "book-service"
      APP_PORT: 8082
      DB_URL: ${BOOK_SERVICE_DB_URL}
      DB_USER: ${BOOK_SERVICE_DB_USERNAME}
      DB_PASSWORD: ${BOOK_SERVICE_DB_PASSWORD}
      DB_NAME: ${BOOK_SERVICE_DB_NAME}
      DB_HOST: ${BOOK_SERVICE_DB_HOST}
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
      args:
        APP_PORT: 
    container_name: "user-service"
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      APP_HOST: "user-service"
      APP_PORT: 8083
      DB_URL: ${USER_SERVICE_DB_URL}
      DB_USER: ${USER_SERVICE_DB_USERNAME}
      DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      DB_NAME: ${USER_SERVICE_DB_NAME}
      DB_HOST: ${USER_SERVICE_DB_HOST}
      REDIS_HOST: ${USER_REDIS_HOST}
      REDIS_PORT: ${USER_REDIS_PORT}
      TOKEN_SECRET: ${USER_TOKEN_SECRET}
    networks:
      - backend


networks:
  backend:
    driver: bridge